---
- name: Verify
  hosts: localhost
  connection: local

  vars:
    ansible_python_interpreter: '{{ ansible_playbook_python }}'
    test_keys:
      - key: foo
        value: bar
      - key: fizz
        value: buzz

  tasks:
    - name: Get mcrouter Pod data
      k8s_facts:
        kind: Pod
        namespace: '{{ namespace }}'
        label_selectors:
          - app=mcrouter
      register: mcrouter_pod

    - name: Set variable with mcrouter IP
      set_fact:
        mcrouter_pod_ip: "{{ mcrouter_pod.resources[0].status.podIP }}"

    - name: Test setting keys via mcrouter
      script: ./membash.sh -h {{ mcrouter_pod_ip }} -p 5000 set {{ item.key }} 0 {{ item.value }}
      register: membash_key
      delegate_to: "{{ groups.k8s[0] }}"
      with_items: "{{ test_keys }}"
      failed_when: membash_key.stdout_lines[0] != 'STORED'

    - name: Test getting keys from mcrouter
      script: ./membash.sh -h {{ mcrouter_pod_ip }} -p 5000 get {{ item.key }}
      register: membash_key
      delegate_to: "{{ groups.k8s[0] }}"
      with_items: "{{ test_keys }}"
      failed_when: membash_key.stdout_lines[0] != item.value

    - name: Ensure there are 2 servers up according to mcrouter
      script: ./membash.sh -h {{ mcrouter_pod_ip }} -p 5000 stats
      register: membash_stats
      delegate_to: "{{ groups.k8s[0] }}"
      failed_when: "'STAT num_servers_up 2' not in membash_stats.stdout"

    - name: Get memcached Pod data
      k8s_facts:
        kind: Pod
        namespace: '{{ namespace }}'
        label_selectors:
          - app=mcrouter-cache
      register: memcached_pods

    - name: Test getting keys directly from memcached pod 0 with IP {{ memcached_pods.resources[0].status.podIP }}
      script: ./membash.sh -h {{ memcached_pods.resources[0].status.podIP }} get {{ item.key }}
      register: membash_key
      delegate_to: "{{ groups.k8s[0] }}"
      with_items: "{{ test_keys }}"
      failed_when: membash_key.stdout_lines[0] != item.value

    - name: Test getting keys directly from memcached pod 1 with IP {{ memcached_pods.resources[1].status.podIP }}
      script: ./membash.sh -h {{ memcached_pods.resources[1].status.podIP }} get {{ item.key }}
      register: membash_key
      delegate_to: "{{ groups.k8s[0] }}"
      with_items: "{{ test_keys }}"
      failed_when: membash_key.stdout_lines[0] != item.value
