---
galaxy_info:
  author: Anshul Behl, John Lieske, Jeff Geerling
  description: An Ansible role which deploys Mcrouter to Kubernetes
  company: Red Hat, Inc

  license: BSD

  min_ansible_version: 2.8

  platforms:
    - name: EL
      versions:
        - all
    - name: Debian
      versions:
        - all

  galaxy_tags:
    - kubernetes
    - operator
    - mcrouter
    - memcached

dependencies: []
